const p_name = [
"owner",
"repo",
"run_id",
"name",
"encrypted_value",
"key_id",
"artifact_id",
"archive_format",
"per_page",
"page",
"runner_id",
"workflow_id",
"job_id",
"actor",
"branch",
"event",
"status",
"thread_id",
"username",
"org",
"all",
"participating",
"since",
"before",
"sort",
"direction",
"last_read_at",
"subscribed",
"ignored",
"installation_id",
"repository_id",
"account_id",
"client_id",
"access_token",
"content_reference_id",
"title",
"body",
"code",
"repository_ids",
"permissions",
"app_slug",
"plan_id",
"head_sha",
"details_url",
"external_id",
"started_at",
"conclusion",
"completed_at",
"output",
"output.title",
"output.summary",
"output.text",
"output.annotations",
"output.annotations[].path",
"output.annotations[].start_line",
"output.annotations[].end_line",
"output.annotations[].start_column",
"output.annotations[].end_column",
"output.annotations[].annotation_level",
"output.annotations[].message",
"output.annotations[].title",
"output.annotations[].raw_details",
"output.images",
"output.images[].alt",
"output.images[].image_url",
"output.images[].caption",
"actions",
"actions[].label",
"actions[].description",
"actions[].identifier",
"check_run_id",
"check_suite_id",
"ref",
"check_name",
"filter",
"app_id",
"auto_trigger_checks",
"auto_trigger_checks[].app_id",
"auto_trigger_checks[].setting",
"key",
"gist_id",
"files",
"files.content",
"description",
"public",
"comment_id",
"sha",
"files.filename",
"content",
"encoding",
"message",
"tree",
"parents",
"author",
"author.name",
"author.email",
"author.date",
"committer",
"committer.name",
"committer.email",
"committer.date",
"signature",
"tag",
"object",
"type",
"tagger",
"tagger.name",
"tagger.email",
"tagger.date",
"tree[].path",
"tree[].mode",
"tree[].type",
"tree[].sha",
"tree[].content",
"base_tree",
"file_sha",
"commit_sha",
"tag_sha",
"tree_sha",
"recursive",
"force",
"limit",
"issue_number",
"assignees",
"labels",
"assignee",
"milestone",
"color",
"state",
"due_on",
"milestone_number",
"event_id",
"creator",
"mentioned",
"lock_reason",
"new_name",
"license",
"text",
"mode",
"context",
"data",
"migration_id",
"author_id",
"email",
"use_lfs",
"repositories",
"lock_repositories",
"exclude_attachments",
"vcs_url",
"vcs",
"vcs_username",
"vcs_password",
"tfvc_project",
"repo_name",
"role",
"config",
"config.url",
"config.content_type",
"config.secret",
"config.insecure_ssl",
"events",
"active",
"invitee_id",
"team_ids",
"hook_id",
"invitation_id",
"billing_email",
"company",
"location",
"has_organization_projects",
"has_repository_projects",
"default_repository_permission",
"members_can_create_repositories",
"members_can_create_internal_repositories",
"members_can_create_private_repositories",
"members_can_create_public_repositories",
"members_allowed_repository_creation_type",
"project_id",
"permission",
"column_id",
"note",
"content_id",
"content_type",
"card_id",
"archived_state",
"affiliation",
"position",
"organization_permission",
"private",
"archived",
"pull_number",
"head",
"base",
"maintainer_can_modify",
"draft",
"commit_id",
"path",
"side",
"line",
"start_line",
"start_side",
"comments",
"comments[].path",
"comments[].position",
"comments[].body",
"reviewers",
"team_reviewers",
"review_id",
"commit_title",
"commit_message",
"merge_method",
"expected_head_sha",
"team_slug",
"discussion_number",
"comment_number",
"reaction_id",
"read_only",
"apps",
"contexts",
"teams",
"users",
"task",
"auto_merge",
"required_contexts",
"payload",
"environment",
"transient_environment",
"production_environment",
"deployment_id",
"target_url",
"log_url",
"environment_url",
"auto_inactive",
"event_type",
"client_payload",
"homepage",
"visibility",
"has_issues",
"has_projects",
"has_wiki",
"is_template",
"team_id",
"auto_init",
"gitignore_template",
"license_template",
"allow_squash_merge",
"allow_merge_commit",
"allow_rebase_merge",
"delete_branch_on_merge",
"organization",
"tag_name",
"target_commitish",
"prerelease",
"template_owner",
"template_repo",
"download_id",
"release_id",
"asset_id",
"source",
"source.branch",
"source.path",
"per",
"status_id",
"build_id",
"protected",
"until",
"anon",
"names",
"new_owner",
"default_branch",
"required_status_checks",
"required_status_checks.strict",
"required_status_checks.contexts",
"enforce_admins",
"required_pull_request_reviews",
"required_pull_request_reviews.dismissal_restrictions",
"required_pull_request_reviews.dismissal_restrictions.users",
"required_pull_request_reviews.dismissal_restrictions.teams",
"required_pull_request_reviews.dismiss_stale_reviews",
"required_pull_request_reviews.require_code_owner_reviews",
"required_pull_request_reviews.required_approving_review_count",
"restrictions",
"restrictions.users",
"restrictions.teams",
"restrictions.apps",
"required_linear_history",
"allow_force_pushes",
"allow_deletions",
"add_events",
"remove_events",
"cname",
"dismissal_restrictions",
"dismissal_restrictions.users",
"dismissal_restrictions.teams",
"dismiss_stale_reviews",
"require_code_owner_reviews",
"required_approving_review_count",
"strict",
"label",
"origin",
"q",
"order",
"maintainers",
"repo_names",
"privacy",
"parent_team_id",
"emails",
"target_user",
"armored_public_key",
"gpg_key_id",
"subject_type",
"subject_id",
"blog",
"hireable",
"bio",
];
const p_desc = [
"owner parameter",
"repo parameter",
"run_id parameter",
"name parameter",
"Value for your secret, encrypted with LibSodium using the public key retrieved from the Get your public key endpoint.",
"ID of the key you used to encrypt the secret.",
"artifact_id parameter",
"archive_format parameter",
"Results per page (max 100)",
"Page number of the results to fetch.",
"runner_id parameter",
"workflow_id parameter",
"job_id parameter",
"Returns someone's workflow runs. Use the login for the user who created the push associated with the check suite or workflow run.",
"Returns workflow runs associated with a branch. Use the name of the branch of the push.",
"Returns workflow run triggered by the event you specify. For example, push, pull_request or issue. For more information, see `Events that trigger workflows` in the GitHub Help documentation.",
"Returns workflow runs associated with the check run status or conclusion you specify. For example, a conclusion can be success or a status can be completed. For more information, see the status and conclusion options available in `Create a check run.`",
"thread_id parameter",
"username parameter",
"org parameter",
"If true, show notifications marked as read.",
"If true, only shows notifications in which the user is directly participating or mentioned.",
"Only show notifications updated after the given time. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.",
"Only show notifications updated before the given time. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.",
"One of created (when the repository was starred) or updated (when it was last pushed to).",
"One of asc (ascending) or desc (descending).",
"Describes the last point that notifications were checked. Anything updated since this time will not be updated. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ. Default: The current timestamp.",
"Determines if notifications should be received from this repository.",
"Determines if all notifications should be blocked from this repository.",
"installation_id parameter",
"repository_id parameter",
"account_id parameter",
"client_id parameter",
"The OAuth access token used to authenticate to the GitHub API.",
"contentreferenceid parameter",
"The title of the content attachment displayed in the body or comment of an issue or pull request.",
"The body text of the content attachment displayed in the body or comment of an issue or pull request. This parameter supports markdown.",
"code parameter",
"The ids of the repositories that the installation token can access. Providing repository ids restricts the access of an installation token to specific repositories. You can use the `List repositories` endpoint to get the id of all repositories that an installation can access. For example, you can select specific repositories when creating an installation token to restrict the number of repositories that can be cloned using the token.",
"The permissions granted to the access token. The permissions object includes the permission names and their access type. For a complete list of permissions and allowable values, see `GitHub App permissions.`",
"app_slug parameter",
"plan_id parameter",
"The SHA of the commit.",
"The URL of the integrator's site that has the full details of the check.",
"A reference for the run on the integrator's system.",
"The time that the check run began. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.",
"Required if you provide completed_at or a status of completed. The final conclusion of the check. Can be one of success, failure, neutral, cancelled, timed_out, or action_required. When the conclusion is action_required, additional details should be provided on the site specified by details_url. Note: Providing conclusion will automatically set the status parameter to completed. Only GitHub can change a check run conclusion to stale.",
"The time the check completed. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.",
"Check runs can accept a variety of data in the output object, including a title and summary and can optionally provide descriptive details about the run. See the output object description.",
"The title of the check run.",
"The summary of the check run. This parameter supports Markdown.",
"The details of the check run. This parameter supports Markdown.",
"Adds information from your analysis to specific lines of code. Annotations are visible on GitHub in the Checks and Files changed tab of the pull request. The Checks API limits the number of annotations to a maximum of 50 per API request. To create more than 50 annotations, you have to make multiple requests to the Update a check run endpoint. Each time you update the check run, annotations are appended to the list of annotations that already exist for the check run. For details about how you can view annotations on GitHub, see `About status checks`. See the annotations object description for details about how to use this parameter.",
"The path of the file to add an annotation to. For example, assets/css/main.css.",
"The start line of the annotation.",
"The end line of the annotation.",
"The start column of the annotation. Annotations only support start_column and end_column on the same line. Omit this parameter if start_line and end_line have different values.",
"The end column of the annotation. Annotations only support start_column and end_column on the same line. Omit this parameter if start_line and end_line have different values.",
"The level of the annotation. Can be one of notice, warning, or failure.",
"A short description of the feedback for these lines of code. The maximum size is 64 KB.",
"The title that represents the annotation. The maximum size is 255 characters.",
"Details about this annotation. The maximum size is 64 KB.",
"Adds images to the output displayed in the GitHub pull request UI. See the images object description for details.",
"The alternative text for the image.",
"The full URL of the image.",
"A short image description.",
"Displays a button on GitHub that can be clicked to alert your app to do additional tasks. For example, a code linting app can display a button that automatically fixes detected errors. The button created in this object is displayed after the check run completes. When a user clicks the button, GitHub sends the check_run.requested_action webhook to your app. Each action includes a label, identifier and description. A maximum of three actions are accepted. See the actions object description. To learn more about check runs and requested actions, see `Check runs and requested actions.` To learn more about check runs and requested actions, see `Check runs and requested actions.`",
"The text to be displayed on a button in the web UI. The maximum size is 20 characters.",
"A short explanation of what this action would do. The maximum size is 40 characters.",
"A reference for the action on the integrator's system. The maximum size is 20 characters.",
"checkrunid parameter",
"checksuiteid parameter",
"ref parameter",
"Returns check runs with the specified name.",
"Filters check runs by their completed_at timestamp. Can be one of latest (returning the most recent check runs) or all.",
"Filters check suites by GitHub App id.",
"Enables or disables automatic creation of CheckSuite events upon pushes to the repository. Enabled by default. See the auto_trigger_checks object description for details.",
"The id of the GitHub App.",
"Set to true to enable automatic creation of CheckSuite events upon pushes to the repository, or false to disable them.",
"key parameter",
"gist_id parameter",
"The filenames and content of each file in the gist. The keys in the files object represent the filename and have the type string.",
"The content of the file.",
"A descriptive name for this gist.",
"When true, the gist will be public and available for anyone to see.",
"comment_id parameter",
"sha parameter",
"The new name for this file. To delete a file, set the value of the filename to null.",
"The new blob's content.",
"The encoding used for content. Currently, `utf-8` and `base64` are supported.",
"The commit message",
"The SHA of the tree object this commit points to",
"The SHAs of the commits that were the parents of this commit. If omitted or empty, the commit will be written as a root commit. For a single parent, an array of one SHA should be provided; for a merge commit, an array of more than one should be provided.",
"Information about the author of the commit. By default, the author will be the authenticated user and the current date. See the author and committer object below for details.",
"The name of the author (or committer) of the commit",
"The email of the author (or committer) of the commit",
"Indicates when this commit was authored (or committed). This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.",
"Information about the person who is making the commit. By default, committer will use the information set in author. See the author and committer object below for details.",
"The name of the author (or committer) of the commit",
"The email of the author (or committer) of the commit",
"Indicates when this commit was authored (or committed). This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.",
"The PGP signature of the commit. GitHub adds the signature to the gpgsig header of the created commit. For a commit signature to be verifiable by Git or GitHub, it must be an ASCII-armored detached PGP signature over the string commit as it would be written to the object database. To pass a signature parameter, you need to first manually create a valid PGP signature, which can be complicated. You may find it easier to use the command line to create signed commits.",
"The tag's name. This is typically a version (e.g., `v0.0.1`).",
"The SHA of the git object this is tagging.",
"The type of the object we're tagging. Normally this is a commit but it can also be a tree or a blob.",
"An object with information about the individual creating the tag.",
"The name of the author of the tag",
"The email of the author of the tag",
"When this object was tagged. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.",
"The file referenced in the tree.",
"The file mode; one of 100644 for file (blob), 100755 for executable (blob), 040000 for subdirectory (tree), 160000 for submodule (commit), or 120000 for a blob that specifies the path of a symlink.",
"Either blob, tree, or commit.",
"The SHA1 checksum ID of the object in the tree. Also called tree.sha. If the value is null then the file will be deleted.",
"The content you want this file to have. GitHub will write this blob out and use that SHA for this entry. Use either this, or tree.sha.",
"The SHA1 of the tree you want to update with new data. If you don't set this, the commit will be created on top of everything; however, it will only contain your change, the rest of your files will show up as deleted.",
"file_sha parameter",
"commit_sha parameter",
"tag_sha parameter",
"tree_sha parameter",
"recursive parameter",
"Indicates whether to force the update or to make sure the update is a fast-forward update. Leaving this out or setting it to false will make sure you're not overwriting work.",
"Specifies the group of GitHub users who can comment, open issues, or create pull requests in public repositories for the given organization. Must be one of: existing_users, contributors_only, or collaborators_only.",
"issue_number parameter",
"Usernames of people to assign this issue to. NOTE: Only users with push access can add assignees to an issue. Assignees are silently ignored otherwise.",
"The name of the label to add to the issue. Must contain at least one label. Note: Alternatively, you can pass a single label as a string or an array of labels directly, but GitHub recommends passing an object with the labels key.",
"assignee parameter",
"The number of the milestone to associate this issue with. NOTE: Only users with push access can set the milestone for new issues. The milestone is silently dropped otherwise.",
"The hexadecimal color code for the label, without the leading #.",
"The state of the milestone. Either open or closed.",
"The milestone due date. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.",
"milestone_number parameter",
"event_id parameter",
"The user that created the issue.",
"A user that's mentioned in the issue.",
"The reason for locking the issue or pull request conversation. Lock will fail if you don't use one of these reasons: * off-topic * too heated * resolved * spam",
"The new name of the label. Emoji can be added to label names, using either native emoji or colon-style markup. For example, typing :strawberry: will render the emoji . For a full list of available emoji and codes, see emoji-cheat-sheet.com.",
"license parameter",
"The Markdown text to render in HTML. Markdown content must be 400 KB or less.",
"The rendering mode. Can be either: * markdown to render a document in plain Markdown, just like README.md files are rendered. * gfm to render a document in GitHub Flavored Markdown, which creates links for user mentions as well as references to SHA-1 hashes, issues, and pull requests.",
"The repository context to use when creating references in gfm mode. Omit this parameter when using markdown mode.",
"data parameter",
"migration_id parameter",
"author_id parameter",
"The new Git author email.",
"Can be one of opt_in (large files will be stored using Git LFS) or opt_out (large files will be removed during the import).",
"An array of repositories to include in the migration.",
"Locks the repositories to prevent changes during the migration when set to true.",
"Does not include attachments uploaded to GitHub.com in the migration data when set to true. Excluding attachments will reduce the migration archive file size.",
"The URL of the originating repository.",
"The originating VCS type. Can be one of subversion, git, mercurial, or tfvc. Please be aware that without this parameter, the import job will take additional time to detect the VCS type before beginning the import. This detection step will be reflected in the response.",
"If authentication is required, the username to provide to vcs_url.",
"If authentication is required, the password to provide to vcs_url.",
"For a tfvc import, the name of the project that is being imported.",
"repo_name parameter",
"The role to give the user in the organization. Can be one of: * admin - The user will become an owner of the organization. * member - The user will become a non-owner member of the organization.",
"Key/value pairs to provide settings for this webhook. These are defined below.",
"The URL to which the payloads will be delivered.",
"The media type used to serialize the payloads. Supported values include json and form. The default is form.",
"If provided, the secret will be used as the key to generate the HMAC hex digest value in the X-Hub-Signature header.",
"Determines whether the SSL certificate of the host for url will be verified when delivering payloads. Supported values include 0 (verification is performed) and 1 (verification is not performed). The default is 0. We strongly recommend not setting this to 1 as you are subject to man-in-the-middle and other attacks.",
"Determines what events the hook is triggered for.",
"Determines if notifications are sent when the webhook is triggered. Set to true to send notifications.",
"Required unless you provide email. GitHub user ID for the person you are inviting.",
"Specify IDs for the teams you want to invite new members to.",
"hook_id parameter",
"invitation_id parameter",
"Billing email address. This address is not publicized.",
"The company name.",
"The location.",
"Toggles whether an organization can use organization projects.",
"Toggles whether repositories that belong to the organization can use repository projects.",
"Default permission level members have for organization repositories: * read - can pull, but not push to or administer this repository. * write - can pull and push, but not administer this repository. * admin - can pull, push, and administer this repository. * none - no permissions granted by default.",
"Toggles the ability of non-admin organization members to create repositories. Can be one of: * true - all organization members can create repositories. * false - only organization owners can create repositories. Default: true Note: A parameter can override this parameter. See members_allowed_repository_creation_type in this table for details. Note: A parameter can override this parameter. See members_allowed_repository_creation_type in this table for details.",
"Toggles whether organization members can create internal repositories, which are visible to all enterprise members. You can only allow members to create internal repositories if your organization is associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+. Can be one of: * true - all organization members can create internal repositories. * false - only organization owners can create internal repositories. Default: true. For more information, see `Restricting repository creation in your organization` in the GitHub Help documentation.",
"Toggles whether organization members can create private repositories, which are visible to organization members with permission. Can be one of: * true - all organization members can create private repositories. * false - only organization owners can create private repositories. Default: true. For more information, see `Restricting repository creation in your organization` in the GitHub Help documentation.",
"Toggles whether organization members can create public repositories, which are visible to anyone. Can be one of: * true - all organization members can create public repositories. * false - only organization owners can create public repositories. Default: true. For more information, see `Restricting repository creation in your organization` in the GitHub Help documentation.",
"Specifies which types of repositories non-admin organization members can create. Can be one of: * all - all organization members can create public and private repositories. * private - members can create private repositories. This option is only available to repositories that are part of an organization on GitHub Enterprise Cloud. * none - only admin members can create repositories. Note: This parameter is deprecated and will be removed in the future. Its return value ignores internal repositories. Using this parameter overrides values set in members_can_create_repositories. See this note for details.",
"project_id parameter",
"The permission to grant the collaborator. Note that, if you choose not to pass any parameters, you'll need to set Content-Length to zero when calling out to this endpoint. For more information, see `HTTP verbs.` Can be one of: * read - can read, but not write to or administer this project. * write - can read and write, but not administer this project. * admin - can read, write and administer this project.",
"column_id parameter",
"The card's note content. Only valid for cards without another type of content, so you must omit when specifying content_id and content_type.",
"The issue or pull request id you want to associate with this card. You can use the List issues for a repository and List pull requests endpoints to find this id. Note: Depending on whether you use the issue id or pull request id, you will need to specify Issue or PullRequest as the content_type.",
"Required if you provide content_id. The type of content you want to associate with this card. Use Issue when content_id is an issue id and use PullRequest when content_id is a pull request id.",
"card_id parameter",
"Filters the project cards that are returned by the card's state. Can be one of all,archived, or not_archived.",
"Filters the collaborators by their affiliation. Can be one of: * outside: Outside collaborators of a project that are not a member of the project's organization. * direct: Collaborators with permissions to a project, regardless of organization membership status. * all: All collaborators the authenticated user can see.",
"Can be one of top, bottom, or after:<card_id>, where <card_id> is the id value of a card in the same column, or in the new column specified by column_id.",
"The permission level that determines whether all members of the project's organization can see and/or make changes to the project. Setting organization_permission is only available for organization projects. If an organization member belongs to a team with a higher level of access or is a collaborator with a higher level of access, their permission level is not lowered by organization_permission. For information on changing access for a team or collaborator, see Add or update team project or Add user as a collaborator.",
"Sets the visibility of a project board. Setting private is only available for organization and user projects. Note: Updating a project's visibility requires admin access to the project.",
"Use true to archive a project card. Specify false if you need to restore a previously archived project card.",
"pull_number parameter",
"The name of the branch where your changes are implemented. For cross-repository pull requests in the same network, namespace head with a user like this: username:branch.",
"The name of the branch you want the changes pulled into. This should be an existing branch on the current repository. You cannot submit a pull request to one repository that requests a merge to a base of another repository.",
"Indicates whether maintainers can modify the pull request.",
"Indicates whether the pull request is a draft. See `Draft Pull Requests` in the GitHub Help documentation to learn more.",
"The SHA of the commit needing a comment. Not using the latest commit SHA may render your comment outdated if a subsequent commit modifies the line you specify as the position.",
"The relative path to the file that necessitates a comment.",
"Required with comfort-fade preview. In a split diff view, the side of the diff that the pull request's changes appear on. Can be LEFT or RIGHT. Use LEFT for deletions that appear in red. Use RIGHT for additions that appear in green or unchanged lines that appear in white and are shown for context. For a multi-line comment, side represents whether the last line of the comment range is a deletion or addition. For more information, see `Diff view options` in the GitHub Help documentation.",
"Required with comfort-fade preview. The line of the blob in the pull request diff that the comment applies to. For a multi-line comment, the last line of the range that your comment applies to.",
"Required when using multi-line comments. To create multi-line comments, you must use the comfort-fade preview header. The start_line is the first line in the pull request diff that your multi-line comment applies to. To learn more about multi-line comments, see `Commenting on a pull request` in the GitHub Help documentation.",
"Required when using multi-line comments. To create multi-line comments, you must use the comfort-fade preview header. The start_side is the starting side of the diff that the comment applies to. Can be LEFT or RIGHT. To learn more about multi-line comments, see `Commenting on a pull request` in the GitHub Help documentation. See side in this table for additional context.",
"Use the following table to specify the location, destination, and contents of the draft review comment.",
"The relative path to the file that necessitates a review comment.",
"The position in the diff where you want to add a review comment. Note this value is not the same as the line number in the file. For help finding the position value, read the note below.",
"Text of the review comment.",
"An array of user logins that will be requested.",
"An array of team slugs that will be requested.",
"review_id parameter",
"Title for the automatic commit message.",
"Extra detail to append to automatic commit message.",
"Merge method to use. Possible values are merge, squash or rebase. Default is merge.",
"The expected SHA of the pull request's HEAD ref. This is the most recent commit on the pull request's branch. If the expected SHA does not match the pull request's HEAD, you will receive a 422 Unprocessable Entity status. You can use the `List commits on a repository` endpoint to find the most recent commit SHA. Default: SHA of the pull request's current HEAD ref.",
"team_slug parameter",
"discussion_number parameter",
"comment_number parameter",
"reaction_id parameter",
"If true, the key will only be able to read repository contents. Otherwise, the key will be able to read and write.",
"apps parameter",
"contexts parameter",
"teams parameter",
"users parameter",
"Specifies a task to execute (e.g., deploy or deploy:migrations).",
"Attempts to automatically merge the default branch into the requested ref, if it's behind the default branch.",
"The status contexts to verify against commit status checks. If you omit this parameter, GitHub verifies all unique contexts before creating a deployment. To bypass checking entirely, pass an empty array. Defaults to all unique contexts.",
"JSON payload with extra information about the deployment.",
"Name for the target deployment environment (e.g., production, staging, qa).",
"Specifies if the given environment is specific to the deployment and will no longer exist at some point in the future. Default: false Note: This parameter requires you to use the application/vnd.github.ant-man-preview+json custom media type. Note: This parameter requires you to use the application/vnd.github.ant-man-preview+json custom media type.",
"Specifies if the given environment is one that end-users directly interact with. Default: true when environment is production and false otherwise. Note: This parameter requires you to use the application/vnd.github.ant-man-preview+json custom media type.",
"deployment_id parameter",
"The target URL to associate with this status. This URL should contain output to keep the user updated while the task is running or serve as historical information for what happened in the deployment. Note: It's recommended to use the log_url parameter, which replaces target_url.",
"The full URL of the deployment's output. This parameter replaces target_url. We will continue to accept target_url to support legacy uses, but we recommend replacing target_url with log_url. Setting log_url will automatically set target_url to the same value. Default: `` Note: This parameter requires you to use the application/vnd.github.ant-man-preview+json custom media type. Note: This parameter requires you to use the application/vnd.github.ant-man-preview+json custom media type.",
"Sets the URL for accessing your environment. Default: `` Note: This parameter requires you to use the application/vnd.github.ant-man-preview+json custom media type. Note: This parameter requires you to use the application/vnd.github.ant-man-preview+json custom media type.",
"Adds a new inactive status to all prior non-transient, non-production environment deployments with the same repository and environment name as the created status's deployment. An inactive status is only added to deployments that had a success state. Default: true Note: To add an inactive status to production environments, you must use the application/vnd.github.flash-preview+json custom media type. Note: This parameter requires you to use the application/vnd.github.ant-man-preview+json custom media type.",
"Required: A custom webhook event name.",
"JSON payload with extra information about the webhook event that your action or worklow may use.",
"A URL with more information about the repository.",
"Can be public or private. If your organization is associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+, visibility can also be internal. For more information, see `Creating an internal repository` in the GitHub Help documentation. The visibility parameter overrides the private parameter when you use both parameters with the nebula-preview preview header.",
"Either true to enable issues for this repository or false to disable them.",
"Either true to enable projects for this repository or false to disable them. Note: If you're creating a repository in an organization that has disabled repository projects, the default is false, and if you pass true, the API returns an error.",
"Either true to enable the wiki for this repository or false to disable it.",
"Either true to make this repo available as a template repository or false to prevent it.",
"The id of the team that will be granted access to this repository. This is only valid when creating a repository in an organization.",
"Pass true to create an initial commit with empty README.",
"Desired language or platform .gitignore template to apply. Use the name of the template without the extension. For example, `Haskell`.",
"Choose an open source license template that best suits your needs, and then use the license keyword as the license_template string. For example, `mit` or `mpl-2.0`.",
"Either true to allow squash-merging pull requests, or false to prevent squash-merging.",
"Either true to allow merging pull requests with a merge commit, or false to prevent merging pull requests with merge commits.",
"Either true to allow rebase-merging pull requests, or false to prevent rebase-merging.",
"Either true to allow automatically deleting head branches when pull requests are merged, or false to prevent automatic deletion.",
"Optional parameter to specify the organization name if forking into an organization.",
"The name of the tag.",
"Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch (usually master).",
"true to identify the release as a prerelease. false to identify the release as a full release.",
"template_owner parameter",
"template_repo parameter",
"download_id parameter",
"release_id parameter",
"asset_id parameter",
"source parameter",
"The repository branch used to publish your site's source files. Can be either master or gh-pages.",
"The repository directory that includes the source files for the Pages site. When branch is master, you can change path to /docs. When branch is gh-pages, you are unable to specify a path other than /.",
"Must be one of: day, week.",
"status_id parameter",
"build_id parameter",
"Setting to true returns only protected branches. When set to false, only unprotected branches are returned. Omitting this parameter returns all branches.",
"Only commits before this date will be returned. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.",
"Set to 1 or true to include anonymous contributors in results.",
"An array of topics to add to the repository. Pass one or more topics to replace the set of existing topics. Send an empty array ([]) to clear all topics from the repository. Note: Topic names cannot contain uppercase letters.",
"Required: The username or organization name the repository will be transferred to.",
"Updates the default branch for this repository.",
"Require status checks to pass before merging. Set to null to disable.",
"Require branches to be up to date before merging.",
"The list of status checks to require in order to merge into this branch",
"Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.",
"Require at least one approving review on a pull request, before merging. Set to null to disable.",
"Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.",
"The list of user logins with dismissal access",
"The list of team slugs with dismissal access",
"Set to true if you want to automatically dismiss approving reviews when someone pushes a new commit.",
"Blocks merging pull requests until code owners review them.",
"Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6.",
"Restrict who can push to the protected branch. User, app, and team restrictions are only available for organization-owned repositories. Set to null to disable.",
"The list of user logins with push access",
"The list of team slugs with push access",
"The list of app slugs with push access",
"Enforces a linear commit Git history, which prevents anyone from pushing merge commits to a branch. Set to true to enforce a linear commit history. Set to false to disable a linear commit Git history. Your repository must allow squash merging or rebase merging before you can enable a linear commit history. Default: false. For more information, see `Requiring a linear commit history` in the GitHub Help documentation.",
"Permits force pushes to the protected branch by anyone with write access to the repository. Set to true to allow force pushes. Set to false or null to block force pushes. Default: false. For more information, see `Enabling force pushes to a protected branch` in the GitHub Help documentation.`",
"Allows deletion of the protected branch by anyone with write access to the repository. Set to false to prevent deletion of the protected branch. Default: false. For more information, see `Enabling force pushes to a protected branch` in the GitHub Help documentation.",
"Determines a list of events to be added to the list of events that the Hook triggers for.",
"Determines a list of events to be removed from the list of events that the Hook triggers for.",
"Specify a custom domain for the repository. Sending a null value will remove the custom domain. For more about custom domains, see `Using a custom domain with GitHub Pages.`",
"Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.",
"The list of user logins with dismissal access",
"The list of team slugs with dismissal access",
"Set to true if you want to automatically dismiss approving reviews when someone pushes a new commit.",
"Blocks merging pull requests until code owners have reviewed.",
"Specifies the number of reviewers required to approve pull requests. Use a number between 1 and 6.",
"Require branches to be up to date before merging.",
"An alternate short description of the asset. Used in place of the filename.",
"The URL origin (protocol + host name + port) is included in upload_url returned in the response of the `Create a release` endpoint",
"The query contains one or more search keywords and qualifiers. Qualifiers allow you to limit your search to specific areas of GitHub. The REST API supports the same qualifiers as GitHub.com. To learn more about the format of the query, see Constructing a search query. See `Searching code` for a detailed list of qualifiers.",
"Determines whether the first search result returned is the highest number of matches (desc) or lowest number of matches (asc). This parameter is ignored unless you provide sort.",
"List GitHub IDs for organization members who will become team maintainers.",
"The full name (e.g., `organization-name/repository-name`) of repositories to add the team to.",
"The level of privacy this team should have. The options are: For a non-nested team: * secret - only visible to organization owners and members of this team. * closed - visible to all members of this organization. Default: secret For a parent or child team: * closed - visible to all members of this organization. Default for child team: closed",
"The ID of a team to set as the parent team.",
"Adds one or more email addresses to your GitHub account. Must contain at least one email address. Note: Alternatively, you can pass a single email address or an array of emails addresses directly, but we recommend that you pass an object using the emails key.",
"target_user parameter",
"Your GPG key, generated in ASCII-armored format. See `Generating a new GPG key` for help creating a GPG key.",
"gpgkeyid parameter",
"Identifies which additional information you'd like to receive about the person's hovercard. Can be organization, repository, issue, pull_request. Required when using subject_id.",
"Uses the ID for the subject_type you specified. Required when using subject_type.",
"The new blog URL of the user.",
"The new hiring availability of the user.",
"The new short biography of the user.",
];
const c_name = [
"actions.cancelWorkflowRun",
"actions.createOrUpdateSecretForRepo",
"actions.createRegistrationToken",
"actions.createRemoveToken",
"actions.deleteArtifact",
"actions.deleteSecretFromRepo",
"actions.downloadArtifact",
"actions.getArtifact",
"actions.getPublicKey",
"actions.getSecret",
"actions.getSelfHostedRunner",
"actions.getWorkflow",
"actions.getWorkflowJob",
"actions.getWorkflowRun",
"actions.listDownloadsForSelfHostedRunnerApplication",
"actions.listJobsForWorkflowRun",
"actions.listRepoWorkflowRuns",
"actions.listRepoWorkflows",
"actions.listSecretsForRepo",
"actions.listSelfHostedRunnersForRepo",
"actions.listWorkflowJobLogs",
"actions.listWorkflowRunArtifacts",
"actions.listWorkflowRunLogs",
"actions.listWorkflowRuns",
"actions.reRunWorkflow",
"actions.removeSelfHostedRunner",
"activity.checkStarringRepo",
"activity.deleteRepoSubscription",
"activity.deleteThreadSubscription",
"activity.getRepoSubscription",
"activity.getThread",
"activity.getThreadSubscription",
"activity.listEventsForOrg",
"activity.listEventsForUser",
"activity.listFeeds",
"activity.listNotifications",
"activity.listNotificationsForRepo",
"activity.listPublicEvents",
"activity.listPublicEventsForOrg",
"activity.listPublicEventsForRepoNetwork",
"activity.listPublicEventsForUser",
"activity.listReceivedEventsForUser",
"activity.listReceivedPublicEventsForUser",
"activity.listRepoEvents",
"activity.listReposStarredByAuthenticatedUser",
"activity.listReposStarredByUser",
"activity.listReposWatchedByUser",
"activity.listStargazersForRepo",
"activity.listWatchedReposForAuthenticatedUser",
"activity.listWatchersForRepo",
"activity.markAsRead",
"activity.markNotificationsAsReadForRepo",
"activity.markThreadAsRead",
"activity.setRepoSubscription",
"activity.setThreadSubscription",
"activity.starRepo",
"activity.unstarRepo",
"apps.addRepoToInstallation",
"apps.checkAccountIsAssociatedWithAny",
"apps.checkAccountIsAssociatedWithAnyStubbed",
"apps.checkToken",
"apps.createContentAttachment",
"apps.createFromManifest",
"apps.createInstallationToken",
"apps.deleteAuthorization",
"apps.deleteInstallation",
"apps.deleteToken",
"apps.getAuthenticated",
"apps.getBySlug",
"apps.getInstallation",
"apps.getOrgInstallation",
"apps.getRepoInstallation",
"apps.getUserInstallation",
"apps.listAccountsUserOrOrgOnPlan",
"apps.listAccountsUserOrOrgOnPlanStubbed",
"apps.listInstallationReposForAuthenticatedUser",
"apps.listInstallations",
"apps.listInstallationsForAuthenticatedUser",
"apps.listMarketplacePurchasesForAuthenticatedUser",
"apps.listMarketplacePurchasesForAuthenticatedUserStubbed",
"apps.listPlans",
"apps.listPlansStubbed",
"apps.listRepos",
"apps.removeRepoFromInstallation",
"apps.resetToken",
"apps.revokeInstallationToken",
"checks.create",
"checks.createSuite",
"checks.get",
"checks.getSuite",
"checks.listAnnotations",
"checks.listForRef",
"checks.listForSuite",
"checks.listSuitesForRef",
"checks.rerequestSuite",
"checks.setSuitesPreferences",
"checks.update",
"codesOfConduct.getConductCode",
"codesOfConduct.getForRepo",
"codesOfConduct.listConductCodes",
"emojis.get",
"gists.checkIsStarred",
"gists.create",
"gists.createComment",
"gists.delete",
"gists.deleteComment",
"gists.fork",
"gists.get",
"gists.getComment",
"gists.getRevision",
"gists.list",
"gists.listComments",
"gists.listCommits",
"gists.listForks",
"gists.listPublic",
"gists.listPublicForUser",
"gists.listStarred",
"gists.star",
"gists.unstar",
"gists.update",
"gists.updateComment",
"git.createBlob",
"git.createCommit",
"git.createRef",
"git.createTag",
"git.createTree",
"DELETE",
"git.getBlob",
"git.getCommit",
"git.getRef",
"git.getTag",
"git.getTree",
"git.listMatchingRefs",
"git.updateRef",
"gitignore.getTemplate",
"gitignore.listTemplates",
"interactions.addOrUpdateRestrictionsForOrg",
"interactions.addOrUpdateRestrictionsForRepo",
"interactions.getRestrictionsForOrg",
"interactions.getRestrictionsForRepo",
"interactions.removeRestrictionsForOrg",
"interactions.removeRestrictionsForRepo",
"issues.addAssignees",
"issues.addLabels",
"issues.checkAssignee",
"issues.create",
"issues.createComment",
"issues.createLabel",
"issues.createMilestone",
"issues.deleteComment",
"issues.deleteLabel",
"issues.deleteMilestone",
"issues.get",
"issues.getComment",
"issues.getEvent",
"issues.getLabel",
"issues.getMilestone",
"issues.list",
"issues.listAssignees",
"issues.listComments",
"issues.listCommentsForRepo",
"issues.listEvents",
"issues.listEventsForRepo",
"issues.listEventsForTimeline",
"issues.listForAuthenticatedUser",
"issues.listForOrg",
"issues.listForRepo",
"issues.listLabelsForMilestone",
"issues.listLabelsForRepo",
"issues.listLabelsOnIssue",
"issues.listMilestonesForRepo",
"issues.lock",
"issues.removeAssignees",
"issues.removeLabel",
"issues.removeLabels",
"issues.replaceLabels",
"issues.unlock",
"issues.update",
"issues.updateComment",
"issues.updateLabel",
"issues.updateMilestone",
"licenses.get",
"licenses.getForRepo",
"licenses.listCommonlyUsed",
"markdown.render",
"markdown.renderRaw",
"meta.get",
"migrations.cancelImport",
"migrations.deleteArchiveForAuthenticatedUser",
"migrations.deleteArchiveForOrg",
"migrations.downloadArchiveForOrg",
"migrations.getArchiveForAuthenticatedUser",
"migrations.getCommitAuthors",
"migrations.getImportProgress",
"migrations.getLargeFiles",
"migrations.getStatusForAuthenticatedUser",
"migrations.getStatusForOrg",
"migrations.listForAuthenticatedUser",
"migrations.listForOrg",
"migrations.listReposForOrg",
"migrations.listReposForUser",
"migrations.mapCommitAuthor",
"migrations.setLfsPreference",
"migrations.startForAuthenticatedUser",
"migrations.startForOrg",
"migrations.startImport",
"migrations.unlockRepoForAuthenticatedUser",
"migrations.unlockRepoForOrg",
"migrations.updateImport",
"orgs.addOrUpdateMembership",
"orgs.blockUser",
"orgs.checkBlockedUser",
"orgs.checkMembership",
"orgs.checkPublicMembership",
"orgs.concealMembership",
"orgs.convertMemberToOutsideCollaborator",
"orgs.createHook",
"orgs.createInvitation",
"orgs.deleteHook",
"orgs.get",
"orgs.getHook",
"orgs.getMembership",
"orgs.getMembershipForAuthenticatedUser",
"orgs.list",
"orgs.listBlockedUsers",
"orgs.listForAuthenticatedUser",
"orgs.listForUser",
"orgs.listHooks",
"orgs.listInstallations",
"orgs.listInvitationTeams",
"orgs.listMembers",
"orgs.listMemberships",
"orgs.listOutsideCollaborators",
"orgs.listPendingInvitations",
"orgs.listPublicMembers",
"orgs.pingHook",
"orgs.publicizeMembership",
"orgs.removeMember",
"orgs.removeMembership",
"orgs.removeOutsideCollaborator",
"orgs.unblockUser",
"orgs.update",
"orgs.updateHook",
"orgs.updateMembership",
"projects.addCollaborator",
"projects.createCard",
"projects.createColumn",
"projects.createForAuthenticatedUser",
"projects.createForOrg",
"projects.createForRepo",
"projects.delete",
"projects.deleteCard",
"projects.deleteColumn",
"projects.get",
"projects.getCard",
"projects.getColumn",
"projects.listCards",
"projects.listCollaborators",
"projects.listColumns",
"projects.listForOrg",
"projects.listForRepo",
"projects.listForUser",
"projects.moveCard",
"projects.moveColumn",
"projects.removeCollaborator",
"projects.reviewUserPermissionLevel",
"projects.update",
"projects.updateCard",
"projects.updateColumn",
"pulls.checkIfMerged",
"pulls.create",
"pulls.createComment",
"pulls.createReview",
"pulls.createReviewCommentReply",
"pulls.createReviewRequest",
"pulls.deleteComment",
"pulls.deletePendingReview",
"pulls.deleteReviewRequest",
"pulls.dismissReview",
"pulls.get",
"pulls.getComment",
"pulls.getCommentsForReview",
"pulls.getReview",
"pulls.list",
"pulls.listComments",
"pulls.listCommentsForRepo",
"pulls.listCommits",
"pulls.listFiles",
"pulls.listReviewRequests",
"pulls.listReviews",
"pulls.merge",
"pulls.submitReview",
"pulls.update",
"pulls.updateBranch",
"pulls.updateComment",
"pulls.updateReview",
"rateLimit.get",
"reactions.createForCommitComment",
"reactions.createForIssue",
"reactions.createForIssueComment",
"reactions.createForPullRequestReviewComment",
"reactions.createForTeamDiscussionCommentInOrg",
"reactions.createForTeamDiscussionInOrg",
"reactions.delete",
"reactions.listForCommitComment",
"reactions.listForIssue",
"reactions.listForIssueComment",
"reactions.listForPullRequestReviewComment",
"reactions.listForTeamDiscussionCommentInOrg",
"reactions.listForTeamDiscussionInOrg",
"repos.acceptInvitation",
"repos.addCollaborator",
"repos.addDeployKey",
"repos.addProtectedBranchAdminEnforcement",
"repos.addProtectedBranchAppRestrictions",
"repos.addProtectedBranchRequiredSignatures",
"repos.addProtectedBranchRequiredStatusChecksContexts",
"repos.addProtectedBranchTeamRestrictions",
"repos.addProtectedBranchUserRestrictions",
"repos.checkCollaborator",
"repos.checkVulnerabilityAlerts",
"repos.compareCommits",
"repos.createCommitComment",
"repos.createDeployment",
"repos.createDeploymentStatus",
"repos.createDispatchEvent",
"repos.createForAuthenticatedUser",
"repos.createFork",
"repos.createHook",
"repos.createInOrg",
"repos.createOrUpdateFile",
"repos.createRelease",
"repos.createStatus",
"repos.createUsingTemplate",
"repos.declineInvitation",
"repos.delete",
"repos.deleteCommitComment",
"repos.deleteDeployment",
"repos.deleteDownload",
"repos.deleteFile",
"repos.deleteHook",
"repos.deleteInvitation",
"repos.deleteRelease",
"repos.deleteReleaseAsset",
"repos.disableAutomatedSecurityFixes",
"repos.disablePagesSite",
"repos.disableVulnerabilityAlerts",
"repos.enableAutomatedSecurityFixes",
"repos.enablePagesSite",
"repos.enableVulnerabilityAlerts",
"repos.get",
"repos.getAppsWithAccessToProtectedBranch",
"repos.getArchiveLink",
"repos.getBranch",
"repos.getBranchProtection",
"repos.getClones",
"repos.getCodeFrequencyStats",
"repos.getCollaboratorPermissionLevel",
"repos.getCombinedStatusForRef",
"repos.getCommit",
"repos.getCommitActivityStats",
"repos.getCommitComment",
"repos.getContents",
"repos.getContributorsStats",
"repos.getDeployKey",
"repos.getDeployment",
"repos.getDeploymentStatus",
"repos.getDownload",
"repos.getHook",
"repos.getLatestPagesBuild",
"repos.getLatestRelease",
"repos.getPages",
"repos.getPagesBuild",
"repos.getParticipationStats",
"repos.getProtectedBranchAdminEnforcement",
"repos.getProtectedBranchPullRequestReviewEnforcement",
"repos.getProtectedBranchRequiredSignatures",
"repos.getProtectedBranchRequiredStatusChecks",
"repos.getProtectedBranchRestrictions",
"repos.getPunchCardStats",
"repos.getReadme",
"repos.getRelease",
"repos.getReleaseAsset",
"repos.getReleaseByTag",
"repos.getTeamsWithAccessToProtectedBranch",
"repos.getTopPaths",
"repos.getTopReferrers",
"repos.getUsersWithAccessToProtectedBranch",
"repos.getViews",
"repos.list",
"repos.listAssetsForRelease",
"repos.listBranches",
"repos.listBranchesForHeadCommit",
"repos.listCollaborators",
"repos.listCommentsForCommit",
"repos.listCommitComments",
"repos.listCommits",
"repos.listContributors",
"repos.listDeployKeys",
"repos.listDeploymentStatuses",
"repos.listDeployments",
"repos.listDownloads",
"repos.listForOrg",
"repos.listForUser",
"repos.listForks",
"repos.listHooks",
"repos.listInvitations",
"repos.listInvitationsForAuthenticatedUser",
"repos.listLanguages",
"repos.listPagesBuilds",
"repos.listProtectedBranchRequiredStatusChecksContexts",
"repos.listPublic",
"repos.listPullRequestsAssociatedWithCommit",
"repos.listReleases",
"repos.listStatusesForRef",
"repos.listTags",
"repos.listTeams",
"repos.listTopics",
"repos.merge",
"repos.pingHook",
"repos.removeBranchProtection",
"repos.removeCollaborator",
"repos.removeDeployKey",
"repos.removeProtectedBranchAdminEnforcement",
"repos.removeProtectedBranchAppRestrictions",
"repos.removeProtectedBranchPullRequestReviewEnforcement",
"repos.removeProtectedBranchRequiredSignatures",
"repos.removeProtectedBranchRequiredStatusChecks",
"repos.removeProtectedBranchRequiredStatusChecksContexts",
"repos.removeProtectedBranchRestrictions",
"repos.removeProtectedBranchTeamRestrictions",
"repos.removeProtectedBranchUserRestrictions",
"repos.replaceProtectedBranchAppRestrictions",
"repos.replaceProtectedBranchRequiredStatusChecksContexts",
"repos.replaceProtectedBranchTeamRestrictions",
"repos.replaceProtectedBranchUserRestrictions",
"repos.replaceTopics",
"repos.requestPageBuild",
"repos.retrieveCommunityProfileMetrics",
"repos.testPushHook",
"repos.transfer",
"repos.update",
"repos.updateBranchProtection",
"repos.updateCommitComment",
"repos.updateHook",
"repos.updateInformationAboutPagesSite",
"repos.updateInvitation",
"repos.updateProtectedBranchPullRequestReviewEnforcement",
"repos.updateProtectedBranchRequiredStatusChecks",
"repos.updateRelease",
"repos.updateReleaseAsset",
"repos.uploadReleaseAsset",
"search.code",
"search.commits",
"search.issuesAndPullRequests",
"search.labels",
"search.repos",
"search.topics",
"search.users",
"teams.addOrUpdateMembershipInOrg",
"teams.addOrUpdateProjectInOrg",
"teams.addOrUpdateRepoInOrg",
"teams.checkManagesRepoInOrg",
"teams.create",
"teams.createDiscussionCommentInOrg",
"teams.createDiscussionInOrg",
"teams.deleteDiscussionCommentInOrg",
"teams.deleteDiscussionInOrg",
"teams.deleteInOrg",
"teams.getByName",
"teams.getDiscussionCommentInOrg",
"teams.getDiscussionInOrg",
"teams.getMembershipInOrg",
"teams.list",
"teams.listChildInOrg",
"teams.listDiscussionCommentsInOrg",
"teams.listDiscussionsInOrg",
"teams.listForAuthenticatedUser",
"teams.listMembersInOrg",
"teams.listPendingInvitationsInOrg",
"teams.listProjectsInOrg",
"teams.listReposInOrg",
"teams.removeMembershipInOrg",
"teams.removeProjectInOrg",
"teams.removeRepoInOrg",
"teams.reviewProjectInOrg",
"teams.updateDiscussionCommentInOrg",
"teams.updateDiscussionInOrg",
"teams.updateInOrg",
"users.addEmails",
"users.block",
"users.checkBlocked",
"users.checkFollowing",
"users.checkFollowingForUser",
"users.createGpgKey",
"users.createPublicKey",
"users.deleteEmails",
"users.deleteGpgKey",
"users.deletePublicKey",
"users.follow",
"users.getAuthenticated",
"users.getByUsername",
"users.getContextForUser",
"users.getGpgKey",
"users.getPublicKey",
"users.list",
"users.listBlocked",
"users.listEmails",
"users.listFollowersForAuthenticatedUser",
"users.listFollowersForUser",
"users.listFollowingForAuthenticatedUser",
"users.listFollowingForUser",
"users.listGpgKeys",
"users.listGpgKeysForUser",
"users.listPublicEmails",
"users.listPublicKeys",
"users.listPublicKeysForUser",
"users.togglePrimaryEmailVisibility",
"users.unblock",
"users.unfollow",
"users.updateAuthenticated",
];
const c_params = [
"!owner;!repo;!run_id",
"!owner;!repo;!name;encrypted_value;key_id",
"!owner;!repo",
"!owner;!repo",
"!owner;!repo;!artifact_id",
"!owner;!repo;!name",
"!owner;!repo;!artifact_id;!archive_format",
"!owner;!repo;!artifact_id",
"!owner;!repo",
"!owner;!repo;!name;per_page;page",
"!owner;!repo;!runner_id",
"!owner;!repo;!workflow_id",
"!owner;!repo;!job_id",
"!owner;!repo;!run_id",
"!owner;!repo",
"!owner;!repo;!run_id;per_page;page",
"!owner;!repo;actor;branch;event;status;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;!job_id;per_page;page",
"!owner;!repo;!run_id;per_page;page",
"!owner;!repo;!run_id;per_page;page",
"!owner;!repo;!workflow_id;actor;branch;event;status;per_page;page",
"!owner;!repo;!run_id",
"!owner;!repo;!runner_id",
"!owner;!repo",
"!owner;!repo",
"!thread_id",
"!owner;!repo",
"!thread_id",
"!thread_id",
"!username;!org;per_page;page",
"!username;per_page;page",
"",
"all;participating;since;before;per_page;page",
"!owner;!repo;all;participating;since;before;per_page;page",
"per_page;page",
"!org;per_page;page",
"!owner;!repo;per_page;page",
"!username;per_page;page",
"!username;per_page;page",
"!username;per_page;page",
"!owner;!repo;per_page;page",
"sort;direction;per_page;page",
"!username;sort;direction;per_page;page",
"!username;per_page;page",
"!owner;!repo;per_page;page",
"per_page;page",
"!owner;!repo;per_page;page",
"last_read_at",
"!owner;!repo;last_read_at",
"!thread_id",
"!owner;!repo;subscribed;ignored",
"!thread_id;ignored",
"!owner;!repo",
"!owner;!repo",
"!installation_id;!repository_id",
"!account_id",
"!account_id",
"!client_id;access_token",
"!content_reference_id;!title;!body",
"!code",
"!installation_id;repository_ids;permissions",
"!client_id;access_token",
"!installation_id",
"!client_id;access_token",
"",
"!app_slug",
"!installation_id",
"!org",
"!owner;!repo",
"!username",
"!plan_id;sort;direction;per_page;page",
"!plan_id;sort;direction;per_page;page",
"!installation_id;per_page;page",
"per_page;page",
"per_page;page",
"per_page;page",
"per_page;page",
"per_page;page",
"per_page;page",
"per_page;page",
"!installation_id;!repository_id",
"!client_id;access_token",
"",
"!owner;!repo;!name;!head_sha;details_url;external_id;status;started_at;conclusion;completed_at;output;!output.title;!output.summary;output.text;output.annotations;!output.annotations[].path;!output.annotations[].start_line;!output.annotations[].end_line;output.annotations[].start_column;output.annotations[].end_column;!output.annotations[].annotation_level;!output.annotations[].message;output.annotations[].title;output.annotations[].raw_details;output.images;!output.images[].alt;!output.images[].image_url;output.images[].caption;actions;!actions[].label;!actions[].description;!actions[].identifier",
"!owner;!repo;!head_sha",
"!owner;!repo;!check_run_id",
"!owner;!repo;!check_suite_id",
"!owner;!repo;!check_run_id;per_page;page",
"!owner;!repo;!ref;check_name;status;filter;per_page;page",
"!owner;!repo;!check_suite_id;check_name;status;filter;per_page;page",
"!owner;!repo;!ref;app_id;check_name;per_page;page",
"!owner;!repo;!check_suite_id",
"!owner;!repo;auto_trigger_checks;!auto_trigger_checks[].app_id;!auto_trigger_checks[].setting",
"!owner;!repo;!check_run_id;name;details_url;external_id;started_at;status;conclusion;completed_at;output;output.title;!output.summary;output.text;output.annotations;!output.annotations[].path;!output.annotations[].start_line;!output.annotations[].end_line;output.annotations[].start_column;output.annotations[].end_column;!output.annotations[].annotation_level;!output.annotations[].message;output.annotations[].title;output.annotations[].raw_details;output.images;!output.images[].alt;!output.images[].image_url;output.images[].caption;actions;!actions[].label;!actions[].description;!actions[].identifier",
"!key",
"!owner;!repo",
"",
"",
"!gist_id",
"!files;files.content;description;public",
"!gist_id;!body",
"!gist_id",
"!gist_id;!comment_id",
"!gist_id",
"!gist_id",
"!gist_id;!comment_id",
"!gist_id;!sha",
"since;per_page;page",
"!gist_id;per_page;page",
"!gist_id;per_page;page",
"!gist_id;per_page;page",
"since;per_page;page",
"!username;since;per_page;page",
"since;per_page;page",
"!gist_id",
"!gist_id",
"!gist_id;description;files;files.content;files.filename",
"!gist_id;!comment_id;!body",
"!owner;!repo;!content;encoding",
"!owner;!repo;!message;!tree;!parents;author;author.name;author.email;author.date;committer;committer.name;committer.email;committer.date;signature",
"!owner;!repo;!ref;!sha",
"!owner;!repo;!tag;!message;!object;!type;tagger;tagger.name;tagger.email;tagger.date",
"!owner;!repo;!tree;tree[].path;tree[].mode;tree[].type;tree[].sha;tree[].content;base_tree",
"!owner;!repo;!ref",
"!owner;!repo;!file_sha",
"!owner;!repo;!commit_sha",
"!owner;!repo;!ref",
"!owner;!repo;!tag_sha",
"!owner;!repo;!tree_sha;recursive",
"!owner;!repo;!ref;per_page;page",
"!owner;!repo;!ref;!sha;force",
"!name",
"",
"!org;!limit",
"!owner;!repo;!limit",
"!org",
"!owner;!repo",
"!org",
"!owner;!repo",
"!owner;!repo;!issue_number;assignees",
"!owner;!repo;!issue_number;!labels",
"!owner;!repo;!assignee",
"!owner;!repo;!title;body;assignee;milestone;labels;assignees",
"!owner;!repo;!issue_number;!body",
"!owner;!repo;!name;!color;description",
"!owner;!repo;!title;state;description;due_on",
"!owner;!repo;!comment_id",
"!owner;!repo;!name",
"!owner;!repo;!milestone_number",
"!owner;!repo;!issue_number",
"!owner;!repo;!comment_id",
"!owner;!repo;!event_id",
"!owner;!repo;!name",
"!owner;!repo;!milestone_number",
"filter;state;labels;sort;direction;since;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;!issue_number;since;per_page;page",
"!owner;!repo;sort;direction;since;per_page;page",
"!owner;!repo;!issue_number;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;!issue_number;per_page;page",
"filter;state;labels;sort;direction;since;per_page;page",
"!org;filter;state;labels;sort;direction;since;per_page;page",
"!owner;!repo;milestone;state;assignee;creator;mentioned;labels;sort;direction;since;per_page;page",
"!owner;!repo;!milestone_number;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;!issue_number;per_page;page",
"!owner;!repo;state;sort;direction;per_page;page",
"!owner;!repo;!issue_number;lock_reason",
"!owner;!repo;!issue_number;assignees",
"!owner;!repo;!issue_number;!name",
"!owner;!repo;!issue_number",
"!owner;!repo;!issue_number;labels",
"!owner;!repo;!issue_number",
"!owner;!repo;!issue_number;title;body;assignee;state;milestone;labels;assignees",
"!owner;!repo;!comment_id;!body",
"!owner;!repo;!name;new_name;color;description",
"!owner;!repo;!milestone_number;title;state;description;due_on",
"!license",
"!owner;!repo",
"",
"!text;mode;context",
"!data",
"",
"!owner;!repo",
"!migration_id",
"!org;!migration_id",
"!org;!migration_id",
"!migration_id",
"!owner;!repo;since",
"!owner;!repo",
"!owner;!repo",
"!migration_id",
"!org;!migration_id",
"per_page;page",
"!org;per_page;page",
"!org;!migration_id;per_page;page",
"!migration_id;per_page;page",
"!owner;!repo;!author_id;email;name",
"!owner;!repo;!use_lfs",
"!repositories;lock_repositories;exclude_attachments",
"!org;!repositories;lock_repositories;exclude_attachments",
"!owner;!repo;!vcs_url;vcs;vcs_username;vcs_password;tfvc_project",
"!migration_id;!repo_name",
"!org;!migration_id;!repo_name",
"!owner;!repo;vcs_username;vcs_password",
"!org;!username;role",
"!org;!username",
"!org;!username",
"!org;!username",
"!org;!username",
"!org;!username",
"!org;!username",
"!org;!name;!config;!config.url;config.content_type;config.secret;config.insecure_ssl;events;active",
"!org;invitee_id;email;role;team_ids",
"!org;!hook_id",
"!org",
"!org;!hook_id",
"!org;!username",
"!org",
"since;per_page;page",
"!org",
"per_page;page",
"!username;per_page;page",
"!org;per_page;page",
"!org;per_page;page",
"!org;!invitation_id;per_page;page",
"!org;filter;role;per_page;page",
"state;per_page;page",
"!org;filter;per_page;page",
"!org;per_page;page",
"!org;per_page;page",
"!org;!hook_id",
"!org;!username",
"!org;!username",
"!org;!username",
"!org;!username",
"!org;!username",
"!org;billing_email;company;email;location;name;description;has_organization_projects;has_repository_projects;default_repository_permission;members_can_create_repositories;members_can_create_internal_repositories;members_can_create_private_repositories;members_can_create_public_repositories;members_allowed_repository_creation_type",
"!org;!hook_id;config;!config.url;config.content_type;config.secret;config.insecure_ssl;events;active",
"!org;!state",
"!project_id;!username;permission",
"!column_id;note;content_id;content_type",
"!project_id;!name",
"!name;body",
"!org;!name;body",
"!owner;!repo;!name;body",
"!project_id",
"!card_id",
"!column_id",
"!project_id",
"!card_id",
"!column_id",
"!column_id;archived_state;per_page;page",
"!project_id;affiliation;per_page;page",
"!project_id;per_page;page",
"!org;state;per_page;page",
"!owner;!repo;state;per_page;page",
"!username;state;per_page;page",
"!card_id;!position;column_id",
"!column_id;!position",
"!project_id;!username",
"!project_id;!username",
"!project_id;name;body;state;organization_permission;private",
"!card_id;note;archived",
"!column_id;!name",
"!owner;!repo;!pull_number",
"!owner;!repo;!title;!head;!base;body;maintainer_can_modify;draft",
"!owner;!repo;!pull_number;!body;!commit_id;!path;position;side;line;start_line;start_side",
"!owner;!repo;!pull_number;commit_id;body;event;comments;!comments[].path;!comments[].position;!comments[].body",
"!owner;!repo;!pull_number;!comment_id;!body",
"!owner;!repo;!pull_number;reviewers;team_reviewers",
"!owner;!repo;!comment_id",
"!owner;!repo;!pull_number;!review_id",
"!owner;!repo;!pull_number;reviewers;team_reviewers",
"!owner;!repo;!pull_number;!review_id;!message",
"!owner;!repo;!pull_number",
"!owner;!repo;!comment_id",
"!owner;!repo;!pull_number;!review_id;per_page;page",
"!owner;!repo;!pull_number;!review_id",
"!owner;!repo;state;head;base;sort;direction;per_page;page",
"!owner;!repo;!pull_number;sort;direction;since;per_page;page",
"!owner;!repo;sort;direction;since;per_page;page",
"!owner;!repo;!pull_number;per_page;page",
"!owner;!repo;!pull_number;per_page;page",
"!owner;!repo;!pull_number;per_page;page",
"!owner;!repo;!pull_number;per_page;page",
"!owner;!repo;!pull_number;commit_title;commit_message;sha;merge_method",
"!owner;!repo;!pull_number;!review_id;body;!event",
"!owner;!repo;!pull_number;title;body;state;base;maintainer_can_modify",
"!owner;!repo;!pull_number;expected_head_sha",
"!owner;!repo;!comment_id;!body",
"!owner;!repo;!pull_number;!review_id;!body",
"",
"!owner;!repo;!comment_id;!content",
"!owner;!repo;!issue_number;!content",
"!owner;!repo;!comment_id;!content",
"!owner;!repo;!comment_id;!content",
"!org;!team_slug;!discussion_number;!comment_number;!content",
"!org;!team_slug;!discussion_number;!content",
"!reaction_id",
"!owner;!repo;!comment_id;content;per_page;page",
"!owner;!repo;!issue_number;content;per_page;page",
"!owner;!repo;!comment_id;content;per_page;page",
"!owner;!repo;!comment_id;content;per_page;page",
"!org;!team_slug;!discussion_number;!comment_number;content;per_page;page",
"!org;!team_slug;!discussion_number;content;per_page;page",
"!invitation_id",
"!owner;!repo;!username;permission",
"!owner;!repo;title;!key;read_only",
"!owner;!repo;!branch",
"!owner;!repo;!branch;!apps",
"!owner;!repo;!branch",
"!owner;!repo;!branch;!contexts",
"!owner;!repo;!branch;!teams",
"!owner;!repo;!branch;!users",
"!owner;!repo;!username",
"!owner;!repo",
"!owner;!repo;!base;!head",
"!owner;!repo;!commit_sha;!body;path;position;line",
"!owner;!repo;!ref;task;auto_merge;required_contexts;payload;environment;description;transient_environment;production_environment",
"!owner;!repo;!deployment_id;!state;target_url;log_url;description;environment;environment_url;auto_inactive",
"!owner;!repo;event_type;client_payload",
"!name;description;homepage;private;visibility;has_issues;has_projects;has_wiki;is_template;team_id;auto_init;gitignore_template;license_template;allow_squash_merge;allow_merge_commit;allow_rebase_merge;delete_branch_on_merge",
"!owner;!repo;organization",
"!owner;!repo;name;!config;!config.url;config.content_type;config.secret;config.insecure_ssl;events;active",
"!org;!name;description;homepage;private;visibility;has_issues;has_projects;has_wiki;is_template;team_id;auto_init;gitignore_template;license_template;allow_squash_merge;allow_merge_commit;allow_rebase_merge;delete_branch_on_merge",
"!owner;!repo;!path;!message;!content;sha;branch;committer;!committer.name;!committer.email;author;!author.name;!author.email",
"!owner;!repo;!tag_name;target_commitish;name;body;draft;prerelease",
"!owner;!repo;!sha;!state;target_url;description;context",
"!template_owner;!template_repo;owner;!name;description;private",
"!invitation_id",
"!owner;!repo",
"!owner;!repo;!comment_id",
"!owner;!repo;!deployment_id",
"!owner;!repo;!download_id",
"!owner;!repo;!path;!message;!sha;branch;committer;committer.name;committer.email;author;author.name;author.email",
"!owner;!repo;!hook_id",
"!owner;!repo;!invitation_id",
"!owner;!repo;!release_id",
"!owner;!repo;!asset_id",
"!owner;!repo",
"!owner;!repo",
"!owner;!repo",
"!owner;!repo",
"!owner;!repo;source;source.branch;source.path",
"!owner;!repo",
"!owner;!repo",
"!owner;!repo;!branch",
"!owner;!repo;!archive_format;!ref",
"!owner;!repo;!branch",
"!owner;!repo;!branch",
"!owner;!repo;per",
"!owner;!repo",
"!owner;!repo;!username",
"!owner;!repo;!ref",
"!owner;!repo;!ref",
"!owner;!repo",
"!owner;!repo;!comment_id",
"!owner;!repo;!path;ref",
"!owner;!repo",
"!owner;!repo;!key_id",
"!owner;!repo;!deployment_id",
"!owner;!repo;!deployment_id;!status_id",
"!owner;!repo;!download_id",
"!owner;!repo;!hook_id",
"!owner;!repo",
"!owner;!repo",
"!owner;!repo",
"!owner;!repo;!build_id",
"!owner;!repo",
"!owner;!repo;!branch",
"!owner;!repo;!branch",
"!owner;!repo;!branch",
"!owner;!repo;!branch",
"!owner;!repo;!branch",
"!owner;!repo",
"!owner;!repo;ref",
"!owner;!repo;!release_id",
"!owner;!repo;!asset_id",
"!owner;!repo;!tag",
"!owner;!repo;!branch",
"!owner;!repo",
"!owner;!repo",
"!owner;!repo;!branch",
"!owner;!repo;per",
"visibility;affiliation;type;sort;direction;per_page;page",
"!owner;!repo;!release_id;per_page;page",
"!owner;!repo;protected;per_page;page",
"!owner;!repo;!commit_sha",
"!owner;!repo;affiliation;per_page;page",
"!owner;!repo;!commit_sha;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;sha;path;author;since;until;per_page;page",
"!owner;!repo;anon;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;!deployment_id;per_page;page",
"!owner;!repo;sha;ref;task;environment;per_page;page",
"!owner;!repo;per_page;page",
"!org;type;sort;direction;per_page;page",
"!username;type;sort;direction;per_page;page",
"!owner;!repo;sort;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;per_page;page",
"per_page;page",
"!owner;!repo",
"!owner;!repo;per_page;page",
"!owner;!repo;!branch",
"since;per_page;page",
"!owner;!repo;!commit_sha;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;!ref;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo;per_page;page",
"!owner;!repo",
"!owner;!repo;!base;!head;commit_message",
"!owner;!repo;!hook_id",
"!owner;!repo;!branch",
"!owner;!repo;!username",
"!owner;!repo;!key_id",
"!owner;!repo;!branch",
"!owner;!repo;!branch;!apps",
"!owner;!repo;!branch",
"!owner;!repo;!branch",
"!owner;!repo;!branch",
"!owner;!repo;!branch;!contexts",
"!owner;!repo;!branch",
"!owner;!repo;!branch;!teams",
"!owner;!repo;!branch;!users",
"!owner;!repo;!branch;!apps",
"!owner;!repo;!branch;!contexts",
"!owner;!repo;!branch;!teams",
"!owner;!repo;!branch;!users",
"!owner;!repo;!names",
"!owner;!repo",
"!owner;!repo",
"!owner;!repo;!hook_id",
"!owner;!repo;new_owner;team_ids",
"!owner;!repo;name;description;homepage;private;visibility;has_issues;has_projects;has_wiki;is_template;default_branch;allow_squash_merge;allow_merge_commit;allow_rebase_merge;delete_branch_on_merge;archived",
"!owner;!repo;!branch;!required_status_checks;!required_status_checks.strict;!required_status_checks.contexts;!enforce_admins;!required_pull_request_reviews;required_pull_request_reviews.dismissal_restrictions;required_pull_request_reviews.dismissal_restrictions.users;required_pull_request_reviews.dismissal_restrictions.teams;required_pull_request_reviews.dismiss_stale_reviews;required_pull_request_reviews.require_code_owner_reviews;required_pull_request_reviews.required_approving_review_count;!restrictions;!restrictions.users;!restrictions.teams;restrictions.apps;required_linear_history;allow_force_pushes;allow_deletions",
"!owner;!repo;!comment_id;!body",
"!owner;!repo;!hook_id;config;!config.url;config.content_type;config.secret;config.insecure_ssl;events;add_events;remove_events;active",
"!owner;!repo;cname;source",
"!owner;!repo;!invitation_id;permissions",
"!owner;!repo;!branch;dismissal_restrictions;dismissal_restrictions.users;dismissal_restrictions.teams;dismiss_stale_reviews;require_code_owner_reviews;required_approving_review_count",
"!owner;!repo;!branch;strict;contexts",
"!owner;!repo;!release_id;tag_name;target_commitish;name;body;draft;prerelease",
"!owner;!repo;!asset_id;name;label",
"!owner;!repo;!release_id;name;label;!data;origin",
"!q;sort;order;per_page;page",
"!q;sort;order;per_page;page",
"!q;sort;order;per_page;page",
"!repository_id;!q;sort;order",
"!q;sort;order;per_page;page",
"!q",
"!q;sort;order;per_page;page",
"!org;!team_slug;!username;role",
"!org;!team_slug;!project_id;permission",
"!org;!team_slug;!owner;!repo;permission",
"!org;!team_slug;!owner;!repo",
"!org;!name;description;maintainers;repo_names;privacy;permission;parent_team_id",
"!org;!team_slug;!discussion_number;!body",
"!org;!team_slug;!title;!body;private",
"!org;!team_slug;!discussion_number;!comment_number",
"!org;!team_slug;!discussion_number",
"!org;!team_slug",
"!org;!team_slug",
"!org;!team_slug;!discussion_number;!comment_number",
"!org;!team_slug;!discussion_number",
"!org;!team_slug;!username",
"!org;per_page;page",
"!org;!team_slug;per_page;page",
"!org;!team_slug;!discussion_number;direction;per_page;page",
"!org;!team_slug;direction;per_page;page",
"per_page;page",
"!org;!team_slug;role;per_page;page",
"!org;!team_slug;per_page;page",
"!org;!team_slug;per_page;page",
"!org;!team_slug;per_page;page",
"!org;!team_slug;!username",
"!org;!team_slug;!project_id",
"!org;!team_slug;!owner;!repo",
"!org;!team_slug;!project_id",
"!org;!team_slug;!discussion_number;!comment_number;!body",
"!org;!team_slug;!discussion_number;title;body",
"!org;!team_slug;!name;description;privacy;permission;parent_team_id",
"!emails",
"!username",
"!username",
"!username",
"!username;!target_user",
"armored_public_key",
"title;key",
"!emails",
"!gpg_key_id",
"!key_id",
"!username",
"",
"!username",
"!username;subject_type;subject_id",
"!gpg_key_id",
"!key_id",
"since;per_page;page",
"",
"per_page;page",
"per_page;page",
"!username;per_page;page",
"per_page;page",
"!username;per_page;page",
"per_page;page",
"!username;per_page;page",
"per_page;page",
"per_page;page",
"!username;per_page;page",
"!email;!visibility",
"!username",
"!username",
"name;email;blog;company;location;hireable;bio",
];
const c_desc = [
"Cancel a workflow run",
"Create or update a secret for a repository",
"Create a registration token",
"Create a remove token",
"Delete an artifact",
"Delete a secret from a repository",
"Download an artifact",
"Get an artifact",
"Get your public key",
"Get a secret",
"Get a self-hosted runner",
"Get a workflow",
"Get a workflow job",
"Get a workflow run",
"List downloads for the self-hosted runner application",
"List jobs for a workflow run",
"List repository workflow runs",
"List repository workflows",
"List secrets for a repository",
"List self-hosted runners for a repository",
"List workflow job logs",
"List workflow run artifacts",
"List workflow run logs",
"List workflow runs",
"Re-run a workflow",
"Remove a self-hosted runner",
"Check if you are starring a repository",
"Delete a Repository Subscription",
"Delete a thread subscription",
"Get a Repository Subscription",
"View a single thread",
"Get a thread subscription",
"List events for an organization",
"List events performed by a user",
"List feeds",
"List your notifications",
"List your notifications in a repository",
"List public events",
"List public events for an organization",
"List public events for a network of repositories",
"List public events performed by a user",
"List events that a user has received",
"List public events that a user has received",
"List repository events",
"List repositories being starred by the authenticated user",
"List repositories being starred by a user",
"List repositories being watched by a user",
"List Stargazers",
"List repositories being watched by the authenticated user",
"List watchers",
"Mark as read",
"Mark notifications as read in a repository",
"Mark a thread as read",
"Set a Repository Subscription",
"Set a thread subscription",
"Star a repository",
"Unstar a repository",
"Add repository to installation",
"Check if a GitHub account is associated with any Marketplace listing",
"Check if a GitHub account is associated with any Marketplace listing (stubbed)",
"Check a token",
"Create a content attachment",
"Create a GitHub App from a manifest",
"Create a new installation token",
"Delete an app authorization",
"Delete an installation",
"Delete an app token",
"Get the authenticated GitHub App",
"Get a single GitHub App",
"Get an installation",
"Get an organization installation",
"Get a repository installation",
"Get a user installation",
"List all GitHub accounts (user or organization) on a specific plan",
"List all GitHub accounts (user or organization) on a specific plan (stubbed)",
"List repositories accessible to the user for an installation",
"List installations",
"List installations for a user",
"Get a user's Marketplace purchases",
"Get a user's Marketplace purchases (stubbed)",
"List all plans for your Marketplace listing",
"List all plans for your Marketplace listing (stubbed)",
"List repositories",
"Remove repository from installation",
"Reset a token",
"Revoke an installation token",
"Create a check run",
"Create a check suite",
"Get a single check run",
"Get a single check suite",
"List annotations for a check run",
"List check runs for a specific ref",
"List check runs in a check suite",
"List check suites for a specific ref",
"Rerequest check suite",
"Set preferences for check suites on a repository",
"Update a check run",
"Get an individual code of conduct",
"Get the contents of a repository's code of conduct",
"List all codes of conduct",
"Get",
"Check if a gist is starred",
"Create a gist",
"Create a comment",
"Delete a gist",
"Delete a comment",
"Fork a gist",
"Get a single gist",
"Get a single comment",
"Get a specific revision of a gist",
"List the authenticated user's gists or if called anonymously, this will return all public gists",
"List comments on a gist",
"List gist commits",
"List gist forks",
"List all public gists",
"List public gists for the specified user",
"List starred gists",
"Star a gist",
"Unstar a gist",
"Edit a gist",
"Edit a comment",
"Create a blob",
"Create a commit",
"Create a reference",
"Create a tag object",
"Create a tree",
"Delete a reference",
"Get a blob",
"Get a commit",
"Get a single reference",
"Get a tag",
"Get a tree",
"List matching references",
"Update a reference",
"Get a single template",
"Listing available templates",
"Add or update interaction restrictions for an organization",
"Add or update interaction restrictions for a repository",
"Get interaction restrictions for an organization",
"Get interaction restrictions for a repository",
"Remove interaction restrictions for an organization",
"Remove interaction restrictions for a repository",
"Add assignees to an issue",
"Add labels to an issue",
"Check assignee",
"Create an issue",
"Create a comment",
"Create a label",
"Create a milestone",
"Delete a comment",
"Delete a label",
"Delete a milestone",
"Get a single issue",
"Get a single comment",
"Get a single event",
"Get a single label",
"Get a single milestone",
"List all issues assigned to the authenticated user across all visible repositories including owned repositories, member repositories, and organization repositories",
"List assignees",
"List comments on an issue",
"List comments in a repository",
"List events for an issue",
"List events for a repository",
"List events for an issue",
"List all issues across owned and member repositories assigned to the authenticated user",
"List all issues for a given organization assigned to the authenticated user",
"List issues for a repository",
"Get labels for every issue in a milestone",
"List all labels for this repository",
"List labels on an issue",
"List milestones for a repository",
"Lock an issue",
"Remove assignees from an issue",
"Remove a label from an issue",
"Remove all labels from an issue",
"Replace all labels for an issue",
"Unlock an issue",
"Edit an issue",
"Edit a comment",
"Update a label",
"Update a milestone",
"Get an individual license",
"Get the contents of a repository's license",
"List commonly used licenses",
"Render an arbitrary Markdown document",
"Render a Markdown document in raw mode",
"Get",
"Cancel an import",
"Delete a user migration archive",
"Delete an organization migration archive",
"Download an organization migration archive",
"Download a user migration archive",
"Get commit authors",
"Get import progress",
"Get large files",
"Get the status of a user migration",
"Get the status of an organization migration",
"List user migrations",
"List organization migrations",
"List repositories in an organization migration",
"List repositories for a user migration",
"Map a commit author",
"Set Git LFS preference",
"Start a user migration",
"Start an organization migration",
"Start an import",
"Unlock a user repository",
"Unlock an organization repository",
"Update existing import",
"Add or update organization membership",
"Block a user",
"Check whether a user is blocked from an organization",
"Check membership",
"Check public membership",
"Conceal a user's membership",
"Convert member to outside collaborator",
"Create a hook",
"Create organization invitation",
"Delete a hook",
"Get an organization",
"Get single hook",
"Get organization membership",
"Get your organization membership",
"List all organizations",
"List blocked users",
"List your organizations",
"List user organizations",
"List hooks",
"List installations for an organization",
"List organization invitation teams",
"Members list",
"List your organization memberships",
"List outside collaborators",
"List pending organization invitations",
"Public members list",
"Ping a hook",
"Publicize a user's membership",
"Remove a member",
"Remove organization membership",
"Remove outside collaborator",
"Unblock a user",
"Edit an organization",
"Edit a hook",
"Edit your organization membership",
"Add user as a collaborator",
"Create a project card",
"Create a project column",
"Create a user project",
"Create an organization project",
"Create a repository project",
"Delete a project",
"Delete a project card",
"Delete a project column",
"Get a project",
"Get a project card",
"Get a project column",
"List project cards",
"List collaborators",
"List project columns",
"List organization projects",
"List repository projects",
"List user projects",
"Move a project card",
"Move a project column",
"Remove user as a collaborator",
"Review a user's permission level",
"Update a project",
"Update a project card",
"Update a project column",
"Get if a pull request has been merged",
"Create a pull request",
"Create a comment",
"Create a pull request review",
"Create a review comment reply",
"Create a review request",
"Delete a comment",
"Delete a pending review",
"Delete a review request",
"Dismiss a pull request review",
"Get a single pull request",
"Get a single comment",
"Get comments for a single review",
"Get a single review",
"List pull requests",
"List comments on a pull request",
"List comments in a repository",
"List commits on a pull request",
"List pull requests files",
"List review requests",
"List reviews on a pull request",
"Merge a pull request (Merge Button)",
"Submit a pull request review",
"Update a pull request",
"Update a pull request branch",
"Edit a comment",
"Update a pull request review",
"Get your current rate limit status",
"Create reaction for a commit comment",
"Create reaction for an issue",
"Create reaction for an issue comment",
"Create reaction for a pull request review comment",
"Create reaction for a team discussion comment",
"Create reaction for a team discussion",
"Delete a reaction",
"List reactions for a commit comment",
"List reactions for an issue",
"List reactions for an issue comment",
"List reactions for a pull request review comment",
"List reactions for a team discussion comment",
"List reactions for a team discussion",
"Accept a repository invitation",
"Add user as a collaborator",
"Add a new deploy key",
"Add admin enforcement of protected branch",
"Add app restrictions of protected branch",
"Add required signatures of protected branch",
"Add required status checks contexts of protected branch",
"Add team restrictions of protected branch",
"Add user restrictions of protected branch",
"Check if a user is a collaborator",
"Check if vulnerability alerts are enabled for a repository",
"Compare two commits",
"Create a commit comment",
"Create a deployment",
"Create a deployment status",
"Create a repository dispatch event",
"Creates a new repository for the authenticated user",
"Create a fork",
"Create a hook",
"Creates a new repository in the specified organization",
"Create or update a file",
"Create a release",
"Create a status",
"Create repository using a repository template",
"Decline a repository invitation",
"Delete a repository",
"Delete a commit comment",
"Delete a deployment",
"Delete a download",
"Delete a file",
"Delete a hook",
"Delete a repository invitation",
"Delete a release",
"Delete a release asset",
"Disable automated security fixes",
"Disable a Pages site",
"Disable vulnerability alerts",
"Enable automated security fixes",
"Enable a Pages site",
"Enable vulnerability alerts",
"Get",
"Get apps with access to protected branch",
"Get archive link",
"Get branch",
"Get branch protection",
"Clones",
"Get the number of additions and deletions per week",
"Review a user's permission level",
"Get the combined status for a specific ref",
"Get a single commit",
"Get the last year of commit activity data",
"Get a single commit comment",
"Get contents",
"Get contributors list with additions, deletions, and commit counts",
"Get a deploy key",
"Get a single deployment",
"Get a single deployment status",
"Get a single download",
"Get single hook",
"Get latest Pages build",
"Get the latest release",
"Get information about a Pages site",
"Get a specific Pages build",
"Get the weekly commit count for the repository owner and everyone else",
"Get admin enforcement of protected branch",
"Get pull request review enforcement of protected branch",
"Get required signatures of protected branch",
"Get required status checks of protected branch",
"Get restrictions of protected branch",
"Get the number of commits per hour in each day",
"Get the README",
"Get a single release",
"Get a single release asset",
"Get a release by tag name",
"Get teams with access to protected branch",
"List paths",
"List referrers",
"Get users with access to protected branch",
"Views",
"List your repositories",
"List assets for a release",
"List branches",
"List branches for HEAD commit",
"List collaborators",
"List comments for a single commit",
"List commit comments for a repository",
"List commits on a repository",
"List contributors",
"List deploy keys",
"List deployment statuses",
"List deployments",
"List downloads for a repository",
"List organization repositories",
"List user repositories",
"List forks",
"List hooks",
"List invitations for a repository",
"List a user's repository invitations",
"List languages",
"List Pages builds",
"List required status checks contexts of protected branch",
"List all public repositories",
"List pull requests associated with commit",
"List releases for a repository",
"List statuses for a specific ref",
"List tags",
"List teams",
"List all topics for a repository",
"Perform a merge",
"Ping a hook",
"Remove branch protection",
"Remove user as a collaborator",
"Remove a deploy key",
"Remove admin enforcement of protected branch",
"Remove app restrictions of protected branch",
"Remove pull request review enforcement of protected branch",
"Remove required signatures of protected branch",
"Remove required status checks of protected branch",
"Remove required status checks contexts of protected branch",
"Remove restrictions of protected branch",
"Remove team restrictions of protected branch",
"Remove user restrictions of protected branch",
"Replace app restrictions of protected branch",
"Replace required status checks contexts of protected branch",
"Replace team restrictions of protected branch",
"Replace user restrictions of protected branch",
"Replace all topics for a repository",
"Request a page build",
"Retrieve community profile metrics",
"Test a push hook",
"Transfer a repository",
"Edit",
"Update branch protection",
"Update a commit comment",
"Edit a hook",
"Update information about a Pages site",
"Update a repository invitation",
"Update pull request review enforcement of protected branch",
"Update required status checks of protected branch",
"Edit a release",
"Edit a release asset",
"Upload a release asset",
"Search code",
"Search commits",
"Search issues and pull requests",
"Search labels",
"Search repositories",
"Search topics",
"Search users",
"Add or update team membership",
"Add or update team project",
"Add or update team repository",
"Check if a team manages a repository",
"Create team",
"Create a comment",
"Create a discussion",
"Delete a comment",
"Delete a discussion",
"Delete team",
"Get team by name",
"Get a single comment",
"Get a single discussion",
"Get team membership",
"List teams",
"List child teams",
"List comments",
"List discussions",
"List user teams",
"List team members",
"List pending team invitations",
"List team projects",
"List team repos",
"Remove team membership",
"Remove team project",
"Remove team repository",
"Review a team project",
"Edit a comment",
"Edit a discussion",
"Edit team",
"Add email address(es)",
"Block a user",
"Check whether you've blocked a user",
"Check if you are following a user",
"Check if one user follows another",
"Create a GPG key",
"Create a public key",
"Delete email address(es)",
"Delete a GPG key",
"Delete a public key",
"Follow a user",
"Get the authenticated user",
"Get a single user",
"Get contextual information about a user",
"Get a single GPG key",
"Get a single public key",
"Get all users",
"List blocked users",
"List email addresses for a user",
"List the authenticated user's followers",
"List a user's followers",
"List who the authenticated user is following",
"List who a user is following",
"List your GPG keys",
"List GPG keys for a user",
"List public email addresses for a user",
"List your public keys",
"List public keys for a user",
"Toggle primary email visibility",
"Unblock a user",
"Unfollow a user",
"Update the authenticated user",
];
const parameters = {name: p_name, desc: p_desc}
const commands = {name: p_name, params: c_params, desc: p_desc}
exports.parameters = parameters;
exports.commands = commands;
